//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jibit.Banking.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BankingErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankingErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jibit.Banking.Resources.BankingErrors", typeof(BankingErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید ای پی آِ وارد شده صحیح نیست..
        /// </summary>
        internal static string apiKey_is_required {
            get {
                return ResourceManager.GetString("apiKey.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک وارد شده نامعتبر است..
        /// </summary>
        internal static string bank_not_valid {
            get {
                return ResourceManager.GetString("bank.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن تاریخ تولد اجباری است..
        /// </summary>
        internal static string birthDate_is_required {
            get {
                return ResourceManager.GetString("birthDate.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد وارد شده نامعتبر است..
        /// </summary>
        internal static string birthDate_not_valid {
            get {
                return ResourceManager.GetString("birthDate.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب نامعتبر است..
        /// </summary>
        internal static string card_account_number_not_valid {
            get {
                return ResourceManager.GetString("card.account_number_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت وارد شده منقضی شده است.
        /// </summary>
        internal static string card_is_expired {
            get {
                return ResourceManager.GetString("card.is_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن شماره کارت اجباری است..
        /// </summary>
        internal static string card_is_required {
            get {
                return ResourceManager.GetString("card.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت وارد شده غیرفعال است..
        /// </summary>
        internal static string card_not_active {
            get {
                return ResourceManager.GetString("card.not_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت وارد شده نامعتبر است..
        /// </summary>
        internal static string card_not_valid {
            get {
                return ResourceManager.GetString("card.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب کارت احراز هویت نکرده است..
        /// </summary>
        internal static string card_owner_not_authorized {
            get {
                return ResourceManager.GetString("card.owner_not_authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت مورد نظر مفقود شده است..
        /// </summary>
        internal static string card_registered_as_lost {
            get {
                return ResourceManager.GetString("card.registered_as_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک مبدا پاسخگو نمی باشد..
        /// </summary>
        internal static string card_source_bank_is_not_active {
            get {
                return ResourceManager.GetString("card.source_bank_is_not_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع کارت پشتیبانی نمی شود..
        /// </summary>
        internal static string card_type_not_supported {
            get {
                return ResourceManager.GetString("card_type.not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست شما با حداکثر میزان خود رسیده است..
        /// </summary>
        internal static string daily_limit_reached {
            get {
                return ResourceManager.GetString("daily_limit.reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب الزامی است..
        /// </summary>
        internal static string deposit_is_required {
            get {
                return ResourceManager.GetString("deposit.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب وارد شده صحیح نیست..
        /// </summary>
        internal static string deposit_length_exceeded {
            get {
                return ResourceManager.GetString("deposit.length_exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب وارد شده نامعتبر است..
        /// </summary>
        internal static string deposit_not_valid {
            get {
                return ResourceManager.GetString("deposit.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن شماره شبا الزامی است..
        /// </summary>
        internal static string iban_is_required {
            get {
                return ResourceManager.GetString("iban.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا وارد شده یافت نشد.
        /// </summary>
        internal static string iban_not_found {
            get {
                return ResourceManager.GetString("iban.not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا وارد شده نامعتبر است..
        /// </summary>
        internal static string iban_not_valid {
            get {
                return ResourceManager.GetString("iban.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب شماره شبا ارسالی یافت نشد..
        /// </summary>
        internal static string iban_owner_not_found {
            get {
                return ResourceManager.GetString("iban.owner_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات هویتی یافت نشد..
        /// </summary>
        internal static string identity_info_not_found {
            get {
                return ResourceManager.GetString("identity_info.not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ورودی نامعتبر است.
        /// </summary>
        internal static string invalid_request_body {
            get {
                return ResourceManager.GetString("invalid.request_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ها مطابقت ندارند..
        /// </summary>
        internal static string names_not_match {
            get {
                return ResourceManager.GetString("names.not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن کدملی الزامی است..
        /// </summary>
        internal static string nationalCode_is_required {
            get {
                return ResourceManager.GetString("nationalCode.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده نامعتبر است..
        /// </summary>
        internal static string nationalCode_not_valid {
            get {
                return ResourceManager.GetString("nationalCode.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی یافت نشد..
        /// </summary>
        internal static string postalCode_not_found {
            get {
                return ResourceManager.GetString("postalCode.not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی وارد شده نامعتبر است..
        /// </summary>
        internal static string postalCode_not_valid {
            get {
                return ResourceManager.GetString("postalCode.not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک در دسترس نیست..
        /// </summary>
        internal static string providers_not_available {
            get {
                return ResourceManager.GetString("providers.not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن کلید خصوصی الزامی است..
        /// </summary>
        internal static string secretKey_is_required {
            get {
                return ResourceManager.GetString("secretKey.is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در سرور رخ داده است..
        /// </summary>
        internal static string server_error {
            get {
                return ResourceManager.GetString("server.error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن توکن الزامی است..
        /// </summary>
        internal static string token_is_required {
            get {
                return ResourceManager.GetString("token.is_required", resourceCulture);
            }
        }
    }
}
